@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.booleanuk.core.Category",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2058424510 { 
   	label=booleanuk
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_543727311 { 
   	label=core
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Category1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)Category</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   BAGEL: Category [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   COFFEE: Category [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   FILLING: Category [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valueOf(name: String): Category</TD></TR>
<TR><TD ALIGN="LEFT" >+ values(): Category[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];

ConditionalDiscount1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConditionalDiscount</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   conditionalItems: Category[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   newPrice: double [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ applyDiscount(order: Order, orders: Order[]): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Discount1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Discount</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ applyDiscount(order: Order, orders: Order[]): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Item1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Item</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   category: Category [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   discount: Discount [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   price: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   uuid: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   variant: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

NumberOfItemsDiscount1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NumberOfItemsDiscount</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   discountPrice: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   itemCount: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ applyDiscount(order: Order, orders: Order[]): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ConditionalDiscount1325589212 -> Category1325589212[label="conditionalItems
[0..*]"];
Discount1325589212 -> ConditionalDiscount1325589212[arrowhead=none, arrowtail=empty, dir=both];
Discount1325589212 -> NumberOfItemsDiscount1325589212[arrowhead=none, arrowtail=empty, dir=both];
Item1325589212 -> Category1325589212[label="category
[0..1]"];
Item1325589212 -> Discount1325589212[label="discount
[0..1]"];
    
}
@enduml