@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.booleanuk.core.Order",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2058424510 { 
   	label=booleanuk
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_543727311 { 
   	label=core
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Basket1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Basket</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   capacity: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orders: ArrayList&lt;Order&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ add(itemID: String, amount: int): Error</TD></TR>
<TR><TD ALIGN="LEFT" >+ addCallback(uuid: String, amount: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ calculateTotalPrice(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ calculateTotalPriceWithDiscounts(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ clearBasket()</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(itemID: String, amount: int): Error</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeCallback(uuid: String, amount: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCapacity(newCapacity: int): Error</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Order1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Order</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   amount: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   itemUUID: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShoppingManager1325589212[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShoppingManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   basket: Basket [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ centerText(text: String, length: int): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ centerText(text: String, length: int, paddingString: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ changeBasketCapacity(newCapacity: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ changeBasketCapacityCallback()</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkout()</TD></TR>
<TR><TD ALIGN="LEFT" >+ doubleToStringFormatter(number: double): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getItem(uuid: String): Item</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPriceCount(uuid: String, count: int): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ isZeroApprox(value: double): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ populateMenu(targetMenu: Menu)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printBasket()</TD></TR>
<TR><TD ALIGN="LEFT" >+ printTotalPrice()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Basket1325589212 -> Order1325589212[label="orders
[0..*]"];
ShoppingManager1325589212 -> Basket1325589212[label="basket
[0..1]"];
    
}
@enduml