@startuml


interface Item{}

enum BagelType implements Item{
    Onion
    Plain
    Everything
    Sesame
}

enum CoffeeType implements Item {
    Black
    White
    Cappuccino
    Latte
}

enum FillingType implements Item {
    Bacon
    Egg
    Creme Cheese
    Smoked Salmon
    Ham
}

class OrderManager {
   -__storeItemInfo__: HashMap<Item, String[]>
   -__storeItemStock__: HashMap<Item, Integer>
   -__defaultMaxBagesl__:int
   -__defaultMaxFillings__:int
   -__defaultMaxCoffees__:int

   - cart: HashMap<Item, Integer>
   - maxCartSize: int

   + getMaxFillings() : int
   + getMaxBagels() : int
   + getMaxCoffees() : int
   + setMaxCartSize(i : int) : void
   + OrderManager()
   + openUpShopAndSetInventory() : void
   + addItem(item : Item) : String
   + getStockOfItem(item : Item) : int
   + getPriceOfItem(item : Item) : double
   + removeItem(item : Item) : String
   + getTotalCartPrice() : double
   + getTotalDiscountedPrice() : double
   + getTotalDiscountRecieptString() : String
   + getTotalDiscountReciept() : Receipt


}

OrderManager -- Item

OrderManager -- Receipt
@enduml