@startuml

Class Basket {
    - basketSize: Integer
    - basket: List<Item, Integer>

    + addItemToBasket(Item item): String
    + removeItemFromBasket(Item item): String

    + basketIsFull(): Boolean
    + itemInBasket(): Boolean

    + calculateBasketCost(): Double
    + changeBasketSize(newSize: Integer): String
}

Abstract Class Item {
    - menu: List<Item>
    - sku: String
    - price: Double
    - name: String
    - variant: String

    + getPrice(): Double
    + getVariant(): String
}

Class Bagel Implements Item {
    - fillings: List<Filling>
    - totalPriceIncludingFillings: Double
    + addFilling(filling: Filling): String
    + getFillings(): List<Filling>
}

Class Filling Implements Item {
}

Class Coffee Implements Item {
}

Class Order {
    - basket: Basket
    + order(): String
}

@enduml

